/* Automatically generated by configure - do not modify */
#define CONFIG_QE_PREFIX "/usr/local"
#define ARCH_X86 1
#define QE_VERSION "0.3.2dev"
#define CONFIG_NETWORK 1
/* #define CONFIG_CYGWIN 1 */
#define CONFIG_WIN32 1
#define CONFIG_HTML 1

#if WIN32
#define inline __inline
typedef unsigned char uint8_t;
#endif
