# Automatically generated by configure - do not modify
prefix=/usr/local
MAKE=make
CC=cl
GCC_MAJOR=3
HOST_CC=cl
AR=ar
STRIP=strip -s -R .comment -R .note
CFLAGS=-O2
LDFLAGS=
EXE=.exe
TARGET_ARCH_X86=yes
EXTRALIBS=-lm
VERSION=0.3.2dev
CONFIG_NETWORK=yes
#CONFIG_CYGWIN=yes
SRC_PATH=/cygdrive/f/kjk/src/tools/qemacs
