# Automatically generated by configure - do not modify
prefix=/usr/local
MAKE=make
CC=gcc
GCC_MAJOR=3
HOST_CC=gcc
AR=ar
STRIP=strip
CFLAGS=-O2
LDFLAGS=
EXE=
TARGET_ARCH_X86=yes
EXTRALIBS=-lm
VERSION=0.3.2dev
CONFIG_NETWORK=yes
SRC_PATH=/Users/kkowalczyk/src/qemacs/src_c
